In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.impute import SimpleImputer
from sklearn.inspection import permutation_importance
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [5]:
data = pd.read_csv(r"C:\Users\user\OneDrive\Dokumente\DATA SCIENCE\1.02.Multiple linear regression.csv")
data.head()
#data.tail()

,SAT,GPA,"Rand 1,2,3"
0,1714,2.40,1
1,1664,2.52,3
2,1760,2.54,3
3,1685,2.74,3
4,1693,2.83,2


In [7]:
data.describe()

,SAT,GPA,"Rand 1,2,3"
count,84.000000,84.000000,84.000000
mean,1845.273810,3.330238,2.059524
std,104.530661,0.271617,0.855192
min,1634.000000,2.400000,1.000000
25%,1772.000000,3.190000,1.000000
50%,1846.000000,3.380000,2.000000
75%,1934.000000,3.502500,3.000000
max,2050.000000,3.810000,3.000000


In [8]:
x = data[["SAT", "Rand 1,2,3"]]
y = data["GPA"]

In [9]:
scaler = StandardScaler()
#Initialize the scaler for the standardization

In [10]:
x_scaled = scaler.fit_transform(x)
#fit and Transform X

In [11]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [12]:
reg= LinearRegression()
reg.fit(x_scaled,y)
#Here we are fitting regression with scaled feautures 

LinearRegression()

In [13]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [12]:
reg.intercept_

np.float64(3.330238095238095)

In [14]:
#Creating a summary table ad showing Bias is same as intercept 
reg_summary = pd.DataFrame([['intercept'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]
print(reg_summary)

     Features   Weights
0   intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030


In [21]:
#Making Predictions with standardized coefficients 

In [22]:
x_new = pd.DataFrame({
    'SAT': [1700, 1800],
    'Rand 1,2,3': [2, 1]
})
#y_pred_manual = (reg.intercept_ + reg.coef_[0] * X_new['SAT']
    #+ reg.coef_[1] * X_new['Rand 1,2,3']
#)
#print(y_pred_manual)
reg.predict(x_new)
#The results we get are not aligning because we have standardized the values which we used to train the regression model

C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [25]:
x_new_scaled=scaler.transform(x_new)
x_new_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [27]:
reg.predict(x_new_scaled)

array([3.09051403, 3.26413803])